# Generated by Django 3.2 on 2021-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Virus',
        ),
    ]
